apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"    
    spec:
      containers:
      - image: pastav/example-voting-app:dotnetv1
        name: worker
